<a href="https://colab.research.google.com/github/NuraddinQJ/AiDojo-Bootcamp/blob/main/Week2_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

## Installing

In [3]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import numpy as np

In [12]:
arr = np.array([1,2,3,4])

print(arr)
print(arr.ndim) #Dimsision
print(arr.shape) #Shaepe
print(arr.dtype) # Data type
print(arr.size)

[1 2 3 4]
1
(4,)
int64
4


In [14]:
def describe_and_display(ar):
    """Print out a summary of an array."""
    print(ar)
    print("-"*50)

    print(f"dimensions: {ar.ndim}")
    print(f"shape: {ar.shape}")
    print(f"size: {ar.size}")
    print(f"dtype: {ar.dtype}")

    print("-"*50)
    print("\n")

# Arrays Example

In [17]:
even=np.array([0,2,4,6])
odd=np.array([1,3,5,7])
arr = np.array([odd,even,odd])

describe_and_display(arr)

[[1 3 5 7]
 [0 2 4 6]
 [1 3 5 7]]
--------------------------------------------------
dimensions: 2
shape: (3, 4)
size: 12
dtype: int64
--------------------------------------------------




## Zeros and Ones

In [24]:
ones = np.ones([3,3])
describe_and_display(ones)

zero= np.zeros([3,3])
describe_and_display(zero)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------
dimensions: 2
shape: (3, 3)
size: 9
dtype: float64
--------------------------------------------------


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------------------------------------
dimensions: 2
shape: (3, 3)
size: 9
dtype: float64
--------------------------------------------------




In [29]:
rng = np.arange(0, 10 ,0.5) #start, end, steps
describe_and_display(rng)

ln = np.linspace(10, 20)
describe_and_display(ln)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
--------------------------------------------------
dimensions: 1
shape: (20,)
size: 20
dtype: float64
--------------------------------------------------


[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]
--------------------------------------------------
dimensions: 1
shape: (50,)
size: 50
dtype: float64
--------------------------------------------------