<a href="https://colab.research.google.com/github/NuraddinQJ/AiDojo-Bootcamp/blob/main/Week4_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning

In [45]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.12.0


In [5]:
# Creta a scalar (rak as 0 tensorflower)
scaler = tf.constant(5)

scaler

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [6]:
# dim of the scaler

scaler.ndim

0

In [11]:
#create a vector (0 dimensions)

vector =tf.constant([1,2,3])
vector.numpy()


array([1, 2, 3], dtype=int32)

In [14]:
#create a matrix more then 1 dimension
matrix= tf.constant([[1,2,3],
                     [3,4,5],
                     [7,8,9]], dtype=tf.int64)

In [15]:
matrix

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])>

In [20]:
tensor = tf.constant([[[1,2,3],
                     [3,4,5],
                     [7,8,9]],
                     [[1,2,3],
                     [3,4,5],
                     [7,8,9]]
                     ], dtype=tf.int64)


In [21]:
tensor.shape

TensorShape([2, 3, 3])

In [24]:
var = tf.Variable([1,2,3])
var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [25]:
var.assign([4,3,4])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 3, 4], dtype=int32)>

In [37]:
tf.random.set_seed(42)

rnd_1 = tf.random.Generator.from_seed(42)
rnd_1 = rnd_1.normal([2])

rnd_2 = tf.random.Generator.from_seed(42)
rnd_2 = rnd_2.normal([2])

rnd_1, rnd_2

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.7565803 , -0.06854702], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.7565803 , -0.06854702], dtype=float32)>)

In [52]:
tf.random.shuffle(matrix, seed=42)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[7, 8, 9],
       [1, 2, 3],
       [3, 4, 5]])>